### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by p0358** [zeroKilo/LSX-Dumper#1]
Is it something wrong with my system or Origin added some protections? When replacing the DLL, Origin doesn't start. Origin.exe appears for a second in taskmgr with like 20K memory and shortly after it disappears. Tried with both your libraries and self-compiled + winhttp from my system

**Comment by zeroKilo** [comment]
well, simplest thing would be trying to reinstall origin. if you can compiled it, add some debug output and see where it crashes. that would help. Otherwise I will test this out myself as soon as I have time.

greetz

**Comment by zeroKilo** [comment]
I just tested this with version 10.5.46.29856 - 0 and it still works for me, I dont know what your issue could be. are you copying BOTH dlls? (winhttp.dll AND winhttp_org.dll)

**Comment by p0358** [comment]
I was stupid, the culprit was very simple. Permissions. I didn't run Origin as admin. No idea why I didn't think of it back then, while today it came to my mind instantly when I attempted this again. The simple solution was to create empty LSX_Log.txt in Origin dir and adjust its permissions...
