### ISSUE TITLE
Editing the response

### ISSUE THREAD

**Issue by ghost** [zeroKilo/LSX-Dumper#2]
I've tried adding something like this in `myEncrypt` function:
```cpp
char entitlements[] = R"(some
very
long
text)"
char* text = ((char*)*(DWORD*)a2);
char* new_text = nullptr;
new_text = (char*) malloc(strlen(entitlements) + 1);
strcpy(new_text, entitlements);
*(DWORD*)a2 = (DWORD)new_text;
free(text);
```
and it works fine - except for when my text is longer than the one I want to replace, then it crashes the game.

And I don't get something. At first IDA shows the encrypt function declaration as
```cpp
class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> __thiscall Origin::Services::Crypto::SimpleEncryption::encrypt(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &)
```
so I guess in short:
```cpp
class std::string __thiscall Origin::Services::Crypto::SimpleEncryption::encrypt(class std::string const &)
```
but later, after autoanalysis it's
```cpp
int __stdcall Origin::Services::Crypto::SimpleEncryption::encrypt(int, void *Src)
```
---
Do you have any tips on how to properly edit the response?

**Comment by zeroKilo** [comment]
well first off, you take over the original function, inside the memory. it gets passed string pointers it allocated and which it later deallocates too. if you overwrite more memory than allocated it will crash on freeing that string somewhere else. the better idea would be to make a mitm lsx service, redirect the game to use another port and edit the responses while you receive/send them inside your mitm tool, this way you control when data is freed. just an idea. also iirc only the result counts, so maybe dont modefy the input string at all, but copy it and work with that, freeing it before you exit the function

mfg

**Comment by ghost** [comment]
I'm not overwriting any memory. I'm allocating a new one, writing to it, freeing old memory and returning pointer to the new one. That should work, right?

As for the length, I started reading about assembly some more and I think I've got it. `*(DWORD*)(a2 + 16)` seems to hold it. Modifying it solves the problem. 

**Edit:** my bad, I forgot to add one line to the code snippet - `new_text = (char*) malloc(strlen(entitlements) + 1);`

**Comment by zeroKilo** [comment]
well, so this issue can be closed then?
